os: osx
language: objective-c

jobs:
  include:
    - os: osx
      osx_image: xcode10.3
      env: SWIFT=5.0.1

    - os: osx
      osx_image: xcode11.3
      env: SWIFT=5.1.3

    - os: linux
      dist: xenial
      language: generic
      env: SWIFT=5.0.3

    - os: linux
      dist: xenial
      language: generic
      env: SWIFT=5.1.4

before_install:
  - clang --version
  - . Utilities/install-swift.sh

script:
  - /bin/bash Tests/test-script.sh
