os: linux
dist: bionic
language: generic

jobs:
  include:
    - os: osx
      osx_image: xcode10.3
      env: SWIFT=5.0.1

    - os: osx
      osx_image: xcode11.3
      env: SWIFT=5.1.3

    - os: osx
      osx_image: xcode11.5
      env: SWIFT=5.2.4

    - os: osx
      osx_image: xcode12.2
      env: SWIFT=5.3.1

    - os: linux
      env: SWIFT=5.0.3

    - os: linux
      env: SWIFT=5.1.5

    - os: linux
      env: SWIFT=5.2.5

    - os: linux
      env: SWIFT=5.3.1

before_install:
  - clang --version
  - . Utilities/install-swift.sh

script:
  - /bin/bash Tests/test-script.sh
